if(EXISTS "/Users/michaelspeckhart/Developer/Projects/StrataDB/tests/tests/stratakv_tests-b12d07c_tests.cmake")
  include("/Users/michaelspeckhart/Developer/Projects/StrataDB/tests/tests/stratakv_tests-b12d07c_tests.cmake")
else()
  add_test(stratakv_tests_NOT_BUILT-b12d07c stratakv_tests_NOT_BUILT-b12d07c)
endif()
